# 八字分析任务配置

calculate_bazi:
  description: >
    作为从事命理研究二十三年的资深八字大师，请运用您的专业经验为用户进行精确的八字排盘。

    【求测者信息】
    - 姓名：{name}
    - 性别：{gender}
    - 出生日期：{birth_date}
    - 出生时间：{birth_time}
    - 出生地点：{birth_place}
    - 用户提供的八字：{provided_bazi}

    【当前时间背景】2025年6月，乙巳年午月

    【专业排盘要求】
    1. **八字来源优先级**：
       - 若用户提供准确八字，直接采用（已考虑节气、真太阳时等因素）
       - 若无提供，根据出生信息精确推算

    2. **排盘精度标准**：
       - 年柱：严格按立春节气划分年份
       - 月柱：精确到节气交替时刻
       - 日柱：采用万年历标准算法
       - 时柱：注意子时跨日（23:00-01:00为次日子时）

    3. **输出格式要求**：
       - 四柱干支组合
       - 各柱五行属性标注
       - 日主强弱初判
       - 排盘依据说明

    请直接进行专业分析，无需调用工具。
  expected_output: >
    完整的八字排盘结果，包括：
    - 年柱：天干地支
    - 月柱：天干地支
    - 日柱：天干地支
    - 时柱：天干地支
    - 对应的五行属性
    - 计算过程的说明

analyze_wuxing:
  description: >
    作为五行命理宗师，请基于八字排盘结果进行深度的五行强弱分析。

    【专业分析框架】
    1. **五行分布统计**：
       - 天干五行：逐一分析四个天干的五行属性
       - 地支五行：分析四个地支的本气及藏干五行
       - 综合统计：金木水火土的总体数量分布

    2. **月令司权分析**：
       - 当前月令对各五行的生克影响
       - 得令、失令五行的强弱判断
       - 季节因素对命局的整体影响

    3. **五行强弱评判**：
       - 过旺：超过30%且得月令生扶
       - 偏旺：占比25-30%或得强根
       - 中和：占比15-25%且有根气
       - 偏弱：占比10-15%或根气不足
       - 太弱：占比低于10%或无根

    4. **用神忌神确定**：
       - 用神：平衡命局所需的五行
       - 忌神：破坏命局平衡的五行
       - 喜神：生扶用神的五行
       - 仇神：克制用神的五行

    5. **调候分析**（2025年6月午月背景）：
       - 当前火旺土燥的季节特点
       - 对不同五行命局的影响
       - 调候用神的重要性

    请直接进行专业分析，提供详细的五行平衡报告。
  expected_output: >
    详细的五行分析报告，包括：
    - 五行分布统计（金木水火土的数量和强度）
    - 五行平衡状态评估
    - 用神和忌神的确定
    - 五行相生相克关系分析
    - 对性格和运势的初步影响

interpret_personality:
  description: >
    作为性格命理解析宗师，请基于八字和五行分析，为求测者提供精准的性格特质解读。

    【专业解读维度】
    1. **核心性格特质**：
       - 日主特性：分析日干的基本性格倾向
       - 格局影响：正格、从格、化格对性格的塑造
       - 十神心性：分析命局中十神对性格的影响

    2. **思维行为模式**：
       - 决策风格：理性型、感性型、直觉型
       - 行动模式：主动进取、稳健保守、随机应变
       - 学习方式：逻辑思维、形象思维、体验学习

    3. **情感人际特质**：
       - 情感表达：内敛含蓄、热情外向、理性克制
       - 人际关系：领导型、协调型、追随型
       - 沟通风格：直接坦率、委婉含蓄、幽默风趣

    4. **天赋潜能分析**：
       - 智慧类型：文学才华、逻辑思维、艺术天赋、管理能力
       - 特殊技能：洞察力、创造力、执行力、感召力
       - 发展方向：学术研究、商业经营、艺术创作、公共服务

    5. **性格优化建议**：
       - 发挥优势：如何最大化性格优点
       - 改善不足：针对性格弱点的具体建议
       - 平衡发展：五行调和对性格完善的作用

    【解读原则】
    - 以传统命理为基础，结合现代心理学理论
    - 注重实用性和可操作性
    - 保持积极正面的表达方式
    - 提供具体的改善建议

    请提供深度专业的性格解读报告。
  expected_output: >
    全面的性格解读报告，包括：
    - 核心性格特质描述
    - 行为模式和思维特点
    - 人际关系和情感特征
    - 天赋才能和职业倾向
    - 性格优势和成长建议
    - 具体的生活指导建议

predict_fortune:
  description: >
    作为运势预测大师，请基于命局分析为求测者提供2025年下半年及未来运势预测。

    【时间背景】2025年6月，乙巳年午月

    【预测时间范围】
    - 近期：2025年7-12月（乙巳年下半年）
    - 中期：2026年丙午年全年
    - 远期：2027年丁未年重点时段

    【专业预测维度】
    1. **整体运势走向**：
       - 大运流年与命局的作用关系
       - 喜忌神在不同时期的影响力
       - 运势起伏的关键转折点

    2. **事业财运分析**：
       - 官杀星、财星在流年的变化
       - 适宜发展的行业和方向
       - 投资理财的吉凶时机
       - 职场人际关系变化

    3. **感情婚姻预测**：
       - 桃花运的旺衰时期
       - 感情发展的有利时机
       - 婚姻关系的稳定性
       - 子女缘分的时间节点

    4. **健康状况评估**：
       - 五行失衡对健康的影响
       - 需要重点关注的身体部位
       - 疾病易发的时间段
       - 养生保健的具体建议

    5. **重要时间节点**：
       - 2025年下半年的关键月份
       - 2026年的重大机遇期
       - 需要谨慎的时间段
       - 适宜重大决策的时机

    【预测方法】
    - 大运流年干支与命局的生克制化
    - 神煞作用的时间效应
    - 五行旺衰的季节变化
    - 十神变化的吉凶影响

    请提供详细准确的运势预测报告。
  expected_output: >
    详细的运势预测报告，包括：
    - 近期整体运势评估
    - 各方面运势的具体分析
    - 重要时间节点的提醒
    - 趋吉避凶的建议
    - 适合进行的活动和决策

provide_life_guidance:
  description: >
    作为人生智慧导师，请整合所有命理分析成果，为求测者制定2025年下半年的人生发展策略。

    【当前时代背景】2025年6月，后疫情时代，AI技术快速发展，经济结构调整期

    【综合指导框架】
    1. **事业发展策略**：
       - 基于命局特点的职业规划
       - 2025-2027年的事业发展路径
       - 适宜的行业选择和转型方向
       - 创业投资的时机把握
       - 职场人际关系的经营策略

    2. **财富管理规划**：
       - 个人理财的五行配置原则
       - 投资方向的吉凶分析
       - 财富积累的最佳时期
       - 风险防范的具体措施
       - 置业购车的时机选择

    3. **感情婚姻指导**：
       - 感情发展的策略建议
       - 婚姻经营的智慧要点
       - 子女教育的命理指导
       - 家庭和谐的维护方法
       - 桃花运的正确把握

    4. **健康养生方案**：
       - 基于五行的养生原则
       - 饮食调理的具体建议
       - 运动健身的最佳方式
       - 作息时间的优化安排
       - 疾病预防的重点关注

    5. **人际关系优化**：
       - 社交圈的构建策略
       - 贵人运的激发方法
       - 小人防范的实用技巧
       - 团队合作的角色定位
       - 人脉资源的有效利用

    6. **个人成长路径**：
       - 性格完善的具体方向
       - 能力提升的重点领域
       - 学习进修的最佳时机
       - 精神修养的实践方法
       - 人生目标的阶段规划

    【指导原则】
    - 命理分析与现代生活相结合
    - 理论指导与实践操作并重
    - 积极正面的人生态度
    - 强调主观能动性的重要作用
    - 提供可量化的行动方案

    【特别关注】
    - 2025年下半年的关键决策点
    - 2026年的重大机遇把握
    - 长期人生规划的战略布局

    请提供全面系统的人生指导方案。
  expected_output: >
    综合性的人生指导报告，包括：
    - 个性化的发展建议
    - 具体的行动计划
    - 需要注意的事项
    - 改运和提升的方法
    - 长期人生规划建议
    - 积极正面的人生态度指导
